export default {
  //Connections
  GET_PROJECTS: 'GET_PROJECTS',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAIL: 'GET_PROJECTS_FAIL',

  GET_PROJECT_README: 'GET_PROJECT_README',
  GET_PROJECT_README_SUCCESS: 'GET_PROJECT_README_SUCCESS',
  GET_PROJECT_README_FAIL: 'GET_PROJECT_README_FAIL',
}

